// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDV1dIxMnhWxPYV6reWlRgmBpxNI-0hAc',
    appId: '1:78944078857:web:d13eb260f6822db46f7cd8',
    messagingSenderId: '78944078857',
    projectId: 'trust-blockchain',
    authDomain: 'trust-blockchain.firebaseapp.com',
    storageBucket: 'trust-blockchain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWH1s6OkVrrxytN5MR4FhO73_iyFDvU8',
    appId: '1:78944078857:android:1db062add278ae9a6f7cd8',
    messagingSenderId: '78944078857',
    projectId: 'trust-blockchain',
    storageBucket: 'trust-blockchain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfOO2BWsyFckz5w0TyTk-0fEhxVhmWONY',
    appId: '1:78944078857:ios:94181570d02cbfa86f7cd8',
    messagingSenderId: '78944078857',
    projectId: 'trust-blockchain',
    storageBucket: 'trust-blockchain.appspot.com',
    iosClientId: '78944078857-l4hnmp16dvam8rv8tvdvrbl1hrobgidn.apps.googleusercontent.com',
    iosBundleId: 'com.example.trustBlockchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfOO2BWsyFckz5w0TyTk-0fEhxVhmWONY',
    appId: '1:78944078857:ios:94181570d02cbfa86f7cd8',
    messagingSenderId: '78944078857',
    projectId: 'trust-blockchain',
    storageBucket: 'trust-blockchain.appspot.com',
    iosClientId: '78944078857-l4hnmp16dvam8rv8tvdvrbl1hrobgidn.apps.googleusercontent.com',
    iosBundleId: 'com.example.trustBlockchain',
  );
}
